# Functions are any command that can be run.
functions:
  checkout:
    - command: git.get_project
      params:
        directory: src
  install:
    - command: subprocess.exec
      params:
        working_dir: src
        shell: bash
        script: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
    - command: subprocess.exec
      params:
        working_dir: src
        shell: bash
        script: |
          nvm install 12.4.0
          nvm alias default 12.4.0
    - command: subprocess.exec
      params:
        working_dir: src
        shell: bash
        script: |
          npm install -g npm@latest
    - command: subprocess.exec
      params:
        working_dir: src
        shell: bash
        script: |
          npm install -g lerna
    - command: subprocess.exec
      params:
        working_dir: src
        shell: bash
        script: |
          npm install
          npm run bootstrap
  check:
    - command: subprocess.exec
      params:
        working_dir: src
        shell: bash
        script: |
          npm run check
  test:
    - command: subprocess.exec
      params:
        working_dir: src
        shell: bash
        script: |
          npm test
  build:
    - command: subprocess.exec
      params:
        working_dir: src
        shell: bash
        script: |
          npm run compile-exec
  publish:
    - command: subprocess.exec
      params:
        working_dir: src
        shell: bash
        script: |
          echo "################# Publish artifacts to S3, NPM and Github ################"
# Tasks will show up as the individual blocks in the Evergreen UI that can
# pass or fail.
tasks:
  - name: install
    commands:
      - func: checkout
      - func: install
  - name: check
    commands:
      - func: checkout
      - func: install
      - func: check
  - name: test
    commands:
      - func: checkout
      - func: install
      - func: test
  - name: build
    commands:
      - func: checkout
      - func: install
      - func: build
  - name: publish
    depends_on:
      - name: check
      - name: test
      - name: build
    commands:
      - func: checkout
      - func: install
      - func: publish
# Need to run builds for every possible build variant.
# TODO: Durran: BUILD-10374 - Need OSX Catalina Signing Machine
buildvariants:
  - name: macos
    display_name: "MacOS Mohave"
    run_on: macos-1014
    tasks:
      - name: install
      - name: check
      - name: test
      - name: build
      - name: publish
#  - name: ubuntu
#    display_name: "Ubuntu 18.04"
#    run_on: ubuntu1804-test
#    tasks:
#      - name: install
#      - name: check
#      - name: test
#      - name: build
#      - name: publish
#  - name: ubuntuppc
#    display_name: "Ubuntu 18.04 PPC"
#    run_on: ubuntu1804-power8-test
#    tasks:
#      - name: install
#      - name: check
#      - name: test
#      - name: build
#      - name: publish
#  - name: ubuntuz
#    display_name: "Ubuntu 18.04 Z Series"
#    run_on: ubuntu1804-zseries-test
#    tasks:
#      - name: install
#      - name: check
#      - name: test
#      - name: build
#      - name: publish
#  - name: rhel7
#    display_name: "RHEL 7.6"
#    run_on: rhel76-test
#    tasks:
#      - name: install
#      - name: check
#      - name: test
#      - name: build
#      - name: publish
#  - name: rhelppc
#    display_name: "RHEL 7.1 PPC"
#    run_on: rhel71-power8-test
#    tasks:
#      - name: install
#      - name: check
#      - name: test
#      - name: build
#      - name: publish
#  - name: rhelz
#    display_name: "RHEL 7.2 Z Series"
#    run_on: rhel72-zseries-test
#    tasks:
#      - name: install
#      - name: check
#      - name: test
#      - name: build
#      - name: publish
