trigger:
  - master
jobs:
  - job: Ubuntu
    pool:
      vmImage: 'ubuntu-latest'
    env:
      MONGOSH_STITCH_TEST_APP_ID: $(MONGOSH_STITCH_TEST_APP_ID)
      MONGOSH_STITCH_TEST_SERVICE_NAME: $(MONGOSH_STITCH_TEST_SERVICE_NAME)
    steps:
      - script: |
          set -e
        displayName: 'Install Services'
      - task: NodeTool@0
        inputs:
          versionSpec: '12.4.0'
        displayName: 'Install Node.js'
      - script: |
          npm install --global lerna
        displayName: 'Install Lerna'
      - script: |
          npm install
        displayName: 'NPM Install'
      - script: |
          lerna run test
        displayName: 'Lerna Run Tests'
      - script: |
          lerna run check
        displayName: 'Lerna Run Checks'
  - job: MacOS
    pool:
      vmImage: 'macOS-latest'
    env:
      MONGOSH_STITCH_TEST_APP_ID: $(MONGOSH_STITCH_TEST_APP_ID)
      MONGOSH_STITCH_TEST_SERVICE_NAME: $(MONGOSH_STITCH_TEST_SERVICE_NAME)
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.4.0'
        displayName: 'Install Node.js'
      - script: |
          npm install --global lerna
        displayName: 'Install Lerna'
      - script: |
          npm install
        displayName: 'NPM Install'
      - script: |
          lerna run test
        displayName: 'Lerna Run Tests'
      - script: |
          lerna run check
        displayName: 'Lerna Run Checks'
  - job: Windows
    pool:
      vmImage: 'windows-latest'
    env:
      MONGOSH_STITCH_TEST_APP_ID: $(MONGOSH_STITCH_TEST_APP_ID)
      MONGOSH_STITCH_TEST_SERVICE_NAME: $(MONGOSH_STITCH_TEST_SERVICE_NAME)
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.4.0'
        displayName: 'Install Node.js'
      - script: |
          npm install --global lerna
        displayName: 'Install Lerna'
      - script: |
          npm install
        displayName: 'NPM Install'
      - script: |
          lerna run test
        displayName: 'Lerna Run Tests'
      - script: |
          lerna run check
        displayName: 'Lerna Run Checks'
