trigger:
  - master
jobs:
  - job: Ubuntu
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          set -e
        displayName: 'Install Services'
      - task: NodeTool@0
        inputs:
          versionSpec: '12.4.0'
        displayName: 'Install Node.js'
      - script: |
          npm install --global lerna
        displayName: 'Install Lerna'
      - script: |
          npm install
        displayName: 'Lerna Bootstrap'
      - script: |
          lerna run test --stream
        displayName: 'Lerna Run Tests'
      - script: |
          lerna run check
        displayName: 'Lerna Run Checks'
  - job: MacOS
    pool:
      vmImage: 'macOS-latest'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.4.0'
        displayName: 'Install Node.js'
      - script: |
          npm install --global lerna
        displayName: 'Install Lerna'
      - script: |
          npm install
        displayName: 'Lerna Bootstrap'
      - script: |
          lerna run test --stream
        displayName: 'Lerna Run Tests'
      - script: |
          lerna run check
        displayName: 'Lerna Run Checks'
  - job: Windows
    pool:
      vmImage: 'windows-latest'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.4.0'
        displayName: 'Install Node.js'
      - script: |
          npm install --global lerna
        displayName: 'Install Lerna'
      - script: |
          npm install
        displayName: 'Lerna Bootstrap'
      - script: |
          lerna run test --stream
        displayName: 'Lerna Run Tests'
      - script: |
          lerna run check
        displayName: 'Lerna Run Checks'
